services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: DB
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3300:3306"